import { StyleSheet } from 'react-native';

export const colors = {
  background: '#0A0D14',
  surface: '#141A26',
  surfaceRaised: '#1B2231',
  border: '#212A3A',
  lavender: '#9DA9FF',
  mint: '#5FE0A8',
  coral: '#FF7A59',
  amber: '#F0B95C',
  textPrimary: '#F2F4F8',
  textSecondary: '#98A1B3',
  textMuted: '#6B7486',
  onAccent: '#0A0D14',
};

export const gradients = {
  continuar: ['#B4BDFF', '#8E9BFF', '#7C8BFF'],
};

export const tint = {
  lavender: 'rgba(157, 169, 255, 0.12)',
  lavenderLine: 'rgba(157, 169, 255, 0.32)',
  mint: 'rgba(95, 224, 168, 0.12)',
  mintLine: 'rgba(95, 224, 168, 0.32)',
  coral: 'rgba(255, 122, 89, 0.12)',
  coralLine: 'rgba(255, 122, 89, 0.32)',
  amber: 'rgba(240, 185, 92, 0.10)',
  amberLine: 'rgba(240, 185, 92, 0.28)',
  neutral: 'rgba(152, 161, 179, 0.10)',
  neutralLine: 'rgba(152, 161, 179, 0.24)',
};

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 14,
    gap: 10,
  },
  backButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  headerStep: {
    color: colors.textMuted,
    fontSize: 13,
    fontVariant: ['tabular-nums'],
  },
  stepper: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  stepperSegment: {
    flex: 1,
    height: 3,
    borderRadius: 999,
    backgroundColor: colors.border,
  },
  stepperSegmentActive: {
    backgroundColor: colors.lavender,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  title: {
    color: colors.textPrimary,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
    letterSpacing: -0.4,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
  },
  provaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 28,
    paddingHorizontal: 20,
    marginTop: 28,
    minHeight: 110,
  },
  provaTexto: {
    flex: 1,
    gap: 8,
  },
  provaNome: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  provaDescricao: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 18,
  },
  provaCheck: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.lavender,
    alignItems: 'center',
    justifyContent: 'center',
  },
  areas: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  areaChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    height: 40,
    width: 100,
    allignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
  },
  areaChipText: {
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  sectionLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1,
    marginTop: 28,
    marginBottom: 10,
  },
  cursoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 16,
    paddingHorizontal: 18,
  },
  cursoRowVazio: {
    borderStyle: 'dashed',
    borderColor: tint.lavenderLine,
    backgroundColor: 'transparent',
  },
  cursoNome: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '500',
  },
  notaCorteCard: {
    marginTop: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: tint.amberLine,
    backgroundColor: tint.amber,
    paddingVertical: 16,
    paddingHorizontal: 18,
    minHeight: 120,
  },
  notaCorteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    fontSize: 11,
  },
  notaIcone: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
    height: 14,
  },
  notaBarra: {
    width: 3,
    borderRadius: 2,
    backgroundColor: colors.amber,
  },
  notaCorteLabel: {
    color: colors.amber,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  notaCorteTexto: {
    color: colors.textPrimary,
    fontSize: 18,
    lineHeight: 21,
    marginTop: 25,
  },
  notaCorteVazia: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 14,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
  },
  continuarWrapper: {
    position: 'relative',
  },
  continuarGlow: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: 10,
    bottom: 0,
    borderRadius: 18,
    backgroundColor: colors.lavender,
    shadowColor: colors.lavender,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 12,
  },
  continuarGlowDisabled: {
    shadowOpacity: 0,
    elevation: 0,
    backgroundColor: 'transparent',
  },
  continuarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 24,
    overflow: 'hidden',
  },
  continuarButtonDisabled: {
    backgroundColor: colors.surfaceRaised,
  },
  continuarText: {
    flex: 1,
    textAlign: 'center',
    color: colors.onAccent,
    fontSize: 16,
    fontWeight: '700',
  },
  continuarSeta: {
    position: 'absolute',
    right: 24,
  },
  pressed: {
    opacity: 0.75,
  },
});
